OBJS =	main.o

NAME = MuntantStack

CXX = c++

CXXFLAGS = -Wall -Wextra -Werror -std=c++11#-std=c++98

all:$(NAME)

$(NAME):$(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re